### ISSUE TITLE
Use sorted(set) when you need ordered output

### ISSUE THREAD

**Issue by mithro** [duck2/uxsdcxx#15]
https://github.com/duck2/uxsdcxx/blob/65c17a2b626e4d2429256db89b5496e2788ffa99/uxsdcxx.py#L457

https://github.com/duck2/uxsdcxx/blob/65c17a2b626e4d2429256db89b5496e2788ffa99/uxsdcxx.py#L456-L467

The Python code you want is;
```python
for i, dfa in enumerate(sorted(t.group_dfas)):
    pass
```

**Comment by mithro** [comment]
There is also http://www.grantjenks.com/docs/sortedcontainers/sortedset.html if speed becomes a problem...

**Comment by duck2** [comment]
This is solved in the latest commit: uxsdcxx gives the same output every time for a given input file.

https://github.com/duck2/uxsdcxx/blob/be0022108e36b9f4eca564e5bd733c1cdb5fd7a1/dfa.py#L162
