### ISSUE TITLE
Generate sane default values

### ISSUE THREAD

**Issue by duck2** [duck2/uxsdcxx#17]
I don't think our structs are zeroing out properly. Inspect and fix this.

Furthermore, default values are used in some optional attributes. It would be good to address this.

**Comment by mithro** [comment]
For the structures to be "Plain Old Data" types, they need to have default values of zero.

**Comment by duck2** [comment]
I think they already have constructors&destructors due to having `unique_ptr`, `vector` and `string`s in them, though.

In fact, it takes considerable time to free the structures. I think this is due to the great number of std::strings.
