### ISSUE TITLE
Load xml into capnp

### ISSUE THREAD

**Issue by duck2** [duck2/uxsdcxx#27]
We can generate cap'n proto schemas and load XML files, but we cannot load XML into the cap'n proto generated structures. Implementing it would be really helpful since a single interface would be enough for handling both Cap'n Proto and XML files.

Preferably, from a `foo.xsd` file, we generate a `foo_uxsdcap.capnp`, `foo_uxsdcap.h` and `foo_uxsdcap.cpp`.

```c++
#include "foo_uxsdcap.capnp.h"
#include "foo_uxsdcap.h"

int main(){
    try {
        ucap::Foo::Reader& foo = ucap::get_root_xml(std::cin);
    } catch {
        std::cout << "PugiXML parse failure\n";
    }
    ucap::put_root_xml(foo, std::cout);
    /* std::cout << foo? */
}
```

**Comment by litghost** [comment]
This has been completed on the interface-consumer branch.
