### ISSUE TITLE
Transfer this repo to SymbiFlow organization

### ISSUE THREAD

**Issue by mithro** [duck2/uxsdcxx#50]
@duck2 - Would you mind transferring this repository to the SymbiFlow organization so that we can do things like merge, update CI, etc.

**Comment by duck2** [comment]
Apparently I don't have the permission to create repos on SymbiFlow. How to go about it?

**Comment by mithro** [comment]
You should have an invite to join the SymbiFlow organization now (which should give you the permission to transfer the repo).

**Comment by duck2** [comment]
done!
