### ISSUE TITLE
Generate a parser from current rr_graph.xsd

### ISSUE THREAD

**Issue by duck2** [duck2/uxsdcxx#7]
To generate a parser from the current rr_graph.xsd, we need:
- [x] Support for `<xs:attribute>`
- [x] Support for loading enumerations in the form of `<xs:restrict`ed `<xs:string>`s.

**Comment by duck2** [comment]
We can generate one now. I'll test it some more before closing this off.

**Comment by mithro** [comment]
Link?

**Comment by duck2** [comment]
here https://gist.github.com/duck2/ebd6f51e8d8494e1885d6a8a35629556

**Comment by duck2** [comment]
The generated parser behaves OK so far.
